# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure(2) do |config|
  config.vm.define 'SDM' do |box|
      box.vm.box = "ubuntu/xenial64"
      box.vm.hostname = 'SDM'
      box.vm.network :private_network, ip: "192.168.10.11"
      box.vm.synced_folder ".", "/vagrant", disabled: false
      box.vm.provider :virtualbox do |vb|
       vb.customize ["modifyvm", :id, "--memory", "4096"]
       vb.customize ["modifyvm", :id, "--cpus", "4"]
      end
      config.vm.provision "docker", images: ["redis", "tensorflow/tensorflow"]
      config.vm.provision "shell", path: "provision.sh"
  end
end
