# -*- mode: ruby -*-
# vi: set ft=ruby :

$provision_script = <<SCRIPT
apt-get update && apt-get -y install python3 python3-pip
apt-get install -y tcpdump tcpreplay jq build-essential

su vagrant -c "python3 -m pip install --user --upgrade pip"
su vagrant -c "python3 -m pip install --user --upgrade jupyter"
su vagrant -c "python3 -m pip install --user --upgrade jupyterlab"

#apt-get install -y luajit
#apt-get -y install lua5.3 luarocks
#su vagrant -c "python3 -m pip install --user --upgrade ilua"
#ln -sf /usr/bin/lua5.3 /usr/bin/lua
SCRIPT

Vagrant.configure(2) do |config|
  config.vm.define 'luabox' do |box|
    box.vm.box = "ubuntu/bionic64"
    box.vm.hostname = 'luabox'
    box.vm.network :private_network, ip: "192.168.10.16"
    box.vm.provider :virtualbox do |vb|
      vb.customize ["modifyvm", :id, "--memory", "2048"]
      vb.customize ["modifyvm", :id, "--cpus", "4"]
    end
    box.vm.provision "docker", images: [
      "docker.elastic.co/elasticsearch/elasticsearch-oss:6.6.0",
    ]
    box.vm.provision "shell", path: "provision.sh"
    box.vm.provision "shell", inline: $provision_script
    box.vm.synced_folder "../vagrant/singlehost", "/singlehost"
    box.vm.synced_folder "./", "/home/vagrant/localbox"
  end
end
