$provision_master = <<SCRIPT

echo "master $1"

apt-get -y install salt-master
systemctl stop salt-master.service
mv /etc/salt/master /etc/salt/master.from_package
echo "open_mode: true" > /etc/salt/master
echo "auto_accept: true" >> /etc/salt/master
systemctl start salt-master.service


INFLUXDB="influxdb_1.2.0_amd64.deb"
cd /vagrant
[[ -f $INFLUXDB ]] || time wget  -q -4 https://dl.influxdata.com/influxdb/releases/$INFLUXDB
dpkg -i $INFLUXDB > /dev/null 2>&1
systemctl stop influxdb.service
sed -i -e 's,# bind-address = ":8086",bind-address = "'${1}':8086",g' /etc/influxdb/influxdb.conf
systemctl start influxdb.service

SCRIPT

$provision_telex = <<SCRIPT

echo "tele $1"

SCRIPT

SALT_MINION_INSTALL_SCRIPT = "../../../common/vagrant/scripts/install-salt-minion.sh"
TELEGRAF_INSTALL_SCRIPT = "../../../common/vagrant/scripts/install-telegraf.sh"

NET = "192.168.12."
NET_START = 10
MASTER_IP = NET + (NET_START).to_s
TELECOUNT = 2

Vagrant.configure(2) do |config|

  config.vm.box = "ubuntu/xenial64"

  config.vm.define 'master' do |box|

      box.vm.hostname = 'master'
      box.vm.network :private_network, ip: MASTER_IP
      box.vm.provider "virtualbox" do |v|
        v.memory = 1024
        v.cpus = 2
      end
      box.vm.provision "shell", inline: $provision_master, args: "#{MASTER_IP}"
      box.vm.provision "shell", path: TELEGRAF_INSTALL_SCRIPT, args: "#{MASTER_IP}"
      box.vm.provision "shell", path: SALT_MINION_INSTALL_SCRIPT, args: "#{MASTER_IP}"

  end

  (1..TELECOUNT).each do |boxno|
    name = "tele-" + boxno.to_s
    ip = NET  + (NET_START + boxno).to_s
    config.vm.define name do |box|
      box.vm.hostname = name
      box.vm.network :private_network, ip: "#{ip}"
      box.vm.provider "virtualbox" do |v|
        v.memory = 512
        v.cpus = 1
      end
      box.vm.provision "shell", path: TELEGRAF_INSTALL_SCRIPT, args: "#{MASTER_IP}"
      box.vm.provision "shell", path: SALT_MINION_INSTALL_SCRIPT, args: "#{MASTER_IP}"
    end
  end
end
