# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure(2) do |config|
  config.vm.define 'rules' do |box|
    box.vm.box = "ubuntu/bionic64"
    box.vm.hostname = 'rules'
    box.vm.network :private_network, ip: "192.168.10.12"
    box.vm.provider :virtualbox do |vb|
     vb.customize ["modifyvm", :id, "--memory", "1024"]
     vb.customize ["modifyvm", :id, "--cpus", "4"]
    end
    box.vm.provision "docker", images: [
      "jasonish/suricata:latest"
    ]
    box.vm.provision "shell", path: "provision.sh"
  end
end
