$SHELL = <<SCRIPT
apt-get update && apt-get install -y git htop vim build-essential
SCRIPT

Vagrant.configure(2) do |config|
  config.vm.define 'suricata-intro' do |box|
    box.vm.box = "ubuntu/bionic64"
    box.vm.hostname = 'suricata-intro'
    box.vm.synced_folder ".", "/vagrant", disabled: false
    box.vm.provider :virtualbox do |vb|
      vb.customize ["modifyvm", :id, "--memory", "1024"]
      vb.customize ["modifyvm", :id, "--cpus", "2"]
    end
    config.vm.provision "shell", inline: $SHELL
  end
end
