IP = "192.168.10.11"
vm_box = 'ubu14'

Vagrant.configure('2') do |config|
  config.vm.define :Amstelredamme do |box|
    box.vm.box = vm_box
    box.vm.synced_folder ".", "/vagrant", disabled: true
    box.vm.network :private_network, ip: "#{IP}"
    box.vm.hostname = 'amstelredamme'
    box.vm.provision :shell, :path => "./SSEE-easybutton-singlehost.sh"
    box.vm.provider :virtualbox do |vb|
     vb.customize ["modifyvm", :id, "--memory", "4096"]
     vb.customize ["modifyvm", :id, "--cpus", "4"]
     end
  end
end
