$provision_script = <<SCRIPT
start=$(date)

cat >> /etc/sysctl.conf <<EOF
net.ipv6.conf.all.disable_ipv6 = 1
net.ipv6.conf.default.disable_ipv6 = 1
net.ipv6.conf.lo.disable_ipv6 = 1
EOF
sysctl -p

echo 'Acquire::ForceIPv4 "true";' | sudo tee /etc/apt/apt.conf.d/99force-ipv4
export DEBIAN_FRONTEND=noninteractive


#set versions here

ELASTICSEARCH="elasticsearch-5.2.1.deb"
EVEBOX="evebox_0.6.0dev~dev20170223182129_amd64.deb"



#suricata
echo "$(date) installing Suricata"
add-apt-repository ppa:oisf/suricata-stable > /dev/null 2>&1
apt-get update > /dev/null 2>&1
apt-get -y install suricata > /dev/null 2>&1
systemctl stop suricata
touch  /etc/suricata//threshold.config
suricata -T -vvv


cd /vagrant

apt-get install openjdk-8-jdk-headless

echo "$(date) installing Elasticsearch"
[[ -f $ELASTICSEARCH ]] || wget  -q -4 https://artifacts.elastic.co/downloads/elasticsearch/$ELASTICSEARCH
dpkg -i $ELASTICSEARCH > /dev/null 2>&1
systemctl stop elasticsearch

[[ -f $EVEBOX ]] ||wget  -q -4 https://bintray.com/jasonish/evebox-development-debian/download_file?file_path=$EVEBOX -O $EVEBOX
dpkg -i $EVEBOX > /dev/null 2>&1


echo "DONE :: start $start end $(date)"
SCRIPT


Vagrant.configure(2) do |config|
  config.vm.define 'Amstelredamme' do |box|
      box.vm.box = "ubuntu/xenial64"
      box.vm.hostname = 'Amstelredamme'
      box.vm.network :private_network, ip: "192.168.10.11"
      box.vm.provider :virtualbox do |vb|
       vb.customize ["modifyvm", :id, "--memory", "4096"]
       vb.customize ["modifyvm", :id, "--cpus", "4"]
      end
      config.vm.provision "shell", inline: $provision_script
  end
end
