# -*- mode: ruby -*-
# vi: set ft=ruby :

$provision_script = <<SCRIPT

echo "dummy"

SCRIPT

Vagrant.configure(2) do |config|
  config.vm.define 'dummy' do |box|
      box.vm.box = "ubuntu/bionic64"
      box.vm.hostname = 'dummy'
      box.vm.network :private_network, ip: "192.168.56.10"
      box.vm.provider :virtualbox do |vb|
       vb.customize ["modifyvm", :id, "--memory", "1024"]
       vb.customize ["modifyvm", :id, "--cpus", "2"]
      end
      config.vm.provision "shell", inline: $provision_script
  end
end
