# -*- mode: ruby -*-
# vi: set ft=ruby :

$provision_script = <<SCRIPT
apt-get update && apt-get -y install python3 python3-pip

su vagrant -c "python3 -m pip install --user --upgrade pip"
su vagrant -c "python3 -m pip install --user --upgrade jupyter"
su vagrant -c "python3 -m pip install --user --upgrade jupyterlab"
su vagrant -c "python3 -m pip install --user --upgrade ilua"
su vagrant -c "python3 -m pip install --user --upgrade pandas"
SCRIPT

Vagrant.configure(2) do |config|
  config.vm.define 'indexer' do |box|
    box.vm.box = "ubuntu/bionic64"
    box.vm.hostname = 'indexer'
    box.vm.network :private_network, ip: "192.168.10.14"
    box.vm.provider :virtualbox do |vb|
      vb.customize ["modifyvm", :id, "--memory", "2048"]
      vb.customize ["modifyvm", :id, "--cpus", "4"]
    end
    box.vm.provision "shell", inline: $provision_script
    box.vm.synced_folder "../setup", "/buildbox"
    box.vm.synced_folder "../rules", "/rulebox"
    box.vm.synced_folder "../../singlehost", "/singlehost"
    box.vm.synced_folder "./", "/home/vagrant/localbox"
  end
end
