# -*- mode: ruby -*-
# vi: set ft=ruby :

# All Vagrant configuration is done below. The "2" in Vagrant.configure
# configures the configuration version (we support older styles for
# backwards compatibility). Please don't change it unless you know what
# you're doing.

$docker = <<-SCRIPT
export DEBIAN_FRONTEND=noninteractive
echo 'Acquire::ForceIPv4 "true";' | sudo tee /etc/apt/apt.conf.d/99force-ipv4
apt-get -qq -y install \
    apt-transport-https \
    ca-certificates \
    curl \
    gnupg-agent \
    software-properties-common
curl -fsSL https://download.docker.com/linux/ubuntu/gpg | apt-key add -
add-apt-repository \
   "deb [arch=amd64] https://download.docker.com/linux/ubuntu \
   $(lsb_release -cs) \
   stable"
apt-get update && apt-get install -qq -y docker-ce docker-ce-cli containerd.io
systemctl enable docker.service
systemctl start docker.service
adduser vagrant docker
SCRIPT

$suricata = <<-SCRIPT
export DEBIAN_FRONTEND=noninteractive
add-apt-repository ppa:oisf/suricata-stable > /dev/null 2>&1 \
&& apt-get update > /dev/null \
&& apt-get install -y suricata > /dev/null

systemctl stop suricata.service
systemctl disable suricata.service
SCRIPT

$suricata_update = <<-SCRIPT
export DEBIAN_FRONTEND=noninteractive
apt-get install -y python3 python3-pip > /dev/null
python3 -m pip install --upgrade --user suricata-update
pip3 install --upgrade suricata-update
suricata-update enable-source tgreen/hunting
suricata-update
SCRIPT

NAME="singlehost"
CPU=4
MEM=4096

Vagrant.configure("2") do |config|
  config.vm.define NAME do |box|
    box.vm.box = "generic/ubuntu2004"
    box.vm.hostname = NAME
    box.vm.provider :virtualbox do |vb|
      vb.customize ["modifyvm", :id, "--memory", MEM]
      vb.customize ["modifyvm", :id, "--cpus", CPU]
    end
    box.vm.provider "libvirt" do |v, override|
      v.cpus = CPU
      v.memory = MEM
      override.vm.synced_folder ".", "/vagrant", type: "rsync"
    end
    box.vm.provider :hyperv do |hv, override|
      hv.cpus = CPU
      hv.maxmemory = MEM
      override.vm.synced_folder ".", "/vagrant", type: "smb"
    end
    box.vm.provider :vmware_desktop do |v, override|
      v.vmx["numvcpus"] = CPU
      v.vmx["memsize"] = MEM
    end
    box.vm.provision "shell", inline: $docker
    box.vm.provision "shell", inline: $suricata
    box.vm.provision "shell", inline: $suricata_update
  end
end
