$provision_script = <<SCRIPT

echo "Building Suricata ..."
apt-get update && apt-get -qq -y install \
libpcre3 \
libpcre3-dbg \
libpcre3-dev \
build-essential \
autoconf \
automake \
libtool \
libpcap-dev \
libnet1-dev \
libyaml-0-2 \
libyaml-dev \
pkg-config \
zlib1g \
zlib1g-dev \
libcap-ng-dev \
libcap-ng0 \
make \
libmagic-dev

cd /home/vagrant
[[ -d suricata ]] || git clone https://github.com/OISF/suricata.git
cd suricata && git checkout tags/suricata-4.0.3

[[ -d libhtp ]] || git clone https://github.com/OISF/libhtp.git
cd libhtp && git checkout tags/0.5.25 && cd ..

pwd
./autogen.sh
./configure

chown -R vagrant:vagrant .

#make && make install

SCRIPT

Vagrant.configure(2) do |config|
  config.vm.define 'buildSuricata' do |box|
      box.vm.box = "ubuntu/xenial64"
      box.vm.hostname = 'buildSuricata'
      box.vm.network :private_network, ip: "192.168.10.12"
      box.vm.provider :virtualbox do |vb|
       vb.customize ["modifyvm", :id, "--memory", "4096"]
       vb.customize ["modifyvm", :id, "--cpus", "4"]
      end
      box.vm.provision "shell", inline: $provision_script
  end
end
