$provision_script = <<SCRIPT

echo "Building Suricata ..."
apt-get update && apt-get install -qq -y \
git \
build-essential \
autogen \
autoconf \
libtool \
pkg-config \
curl \
sudo

cd /vagrant
[[ -d /vagrant/suricata ]] || git clone https://github.com/OISF/suricata \
&& cd /vagrant/suricata \
&& git checkout tags/suricata-4.0.1

cd /vagrant/suricata && git clone https://github.com/OISF/libhtp.git \
&& cd libhtp \
&& git checkout tags/0.5.25

cd /vagrant/suricata && ./autogen.sh

cd /vagrant/suricata && ./configure

#make && make install

SCRIPT

Vagrant.configure(2) do |config|
  config.vm.define 'buildSuricata' do |box|
      box.vm.box = "ubuntu/xenial64"
      box.vm.hostname = 'buildSuricata'
      box.vm.network :private_network, ip: "192.168.10.12"
      box.vm.provider :virtualbox do |vb|
       vb.customize ["modifyvm", :id, "--memory", "4096"]
       vb.customize ["modifyvm", :id, "--cpus", "4"]
      end
      box.vm.provision "shell", inline: $provision_script
  end
end
