# -*- mode: ruby -*-
# vi: set ft=ruby :

NAME = 'day1'.freeze
MEM = 1024
CPU = 4

Vagrant.configure(2) do |config|
  config.vm.define NAME do |box|
    box.vm.box = 'generic/ubuntu2004'
    box.vm.hostname = NAME
    box.vm.synced_folder '..', '/vagrant'
    box.vm.synced_folder '../../', '/cdmcs-suricata'
    box.vm.synced_folder '../../../data/', '/data'
    box.vm.network :private_network, ip: '192.168.56.11'
    box.vm.provider :virtualbox do |vb|
      vb.customize ['modifyvm', :id, '--memory', MEM]
      vb.customize ['modifyvm', :id, '--cpus', CPU]
    end
    box.vm.provision 'docker', images: []
    box.vm.provision 'shell', path: 'provision.sh'
  end
end
