# -*- mode: ruby -*-
# vi: set ft=ruby :

SPLIT_DB_AND_MOLO=true
NAME="student"
BOXES=1
MEM_PER_BOX=2048
CPU_PER_BOX=4

ELA_MEM=2048
ELA_CPU=4

if SPLIT_DB_AND_MOLO == true and MEM_PER_BOX > 2048
  puts "Separate elastic vm will be created. Consider reducing the amount of memory per box"
end

$script = <<-SCRIPT
systemctl stop systemd-resolved.service
echo "nameserver 1.1.1.1" > /etc/resolv.conf
SCRIPT

$docker = <<-SCRIPT
export DEBIAN_FRONTEND=noninteractive
echo 'Acquire::ForceIPv4 "true";' | sudo tee /etc/apt/apt.conf.d/99force-ipv4
apt-get -qq -y install \
    apt-transport-https \
    ca-certificates \
    curl \
    gnupg-agent \
    software-properties-common
curl -fsSL https://download.docker.com/linux/ubuntu/gpg | apt-key add -
add-apt-repository \
   "deb [arch=amd64] https://download.docker.com/linux/ubuntu \
   $(lsb_release -cs) \
   stable"
apt-get update && apt-get install -qq -y docker-ce docker-ce-cli containerd.io
systemctl enable docker.service
systemctl start docker.service
adduser vagrant docker
SCRIPT

PKGDIR="/vagrant/pkgs"
WGET_PARAMS="-4 -q"
MOLOCH="moloch_1.8.0-1_amd64.deb"

$moloch = <<-SCRIPT

FILE=/etc/sysctl.conf
grep "disable_ipv6" $FILE || cat >> $FILE <<EOF
net.ipv6.conf.all.disable_ipv6 = 1
net.ipv6.conf.default.disable_ipv6 = 1
net.ipv6.conf.lo.disable_ipv6 = 1
EOF
grep "vm.max_map_count" $FILE || cat >> $FILE <<EOF
vm.max_map_count=262144
EOF
sysctl -p

mkdir -p #{PKGDIR}
apt-get update && apt-get -y install jq wget curl pcregrep python-minimal python-pip python3-pip python-yaml libpcre3-dev libyaml-dev uuid-dev libmagic-dev pkg-config g++ flex bison zlib1g-dev libffi-dev gettext libgeoip-dev make libjson-perl libbz2-dev libwww-perl libpng-dev xz-utils libffi-dev libsnappy-dev numactl >> /vagrant/provision.log 2>&1

cd #{PKGDIR}
[[ -f #{MOLOCH} ]] || wget #{WGET_PARAMS} https://files.molo.ch/builds/ubuntu-18.04/#{MOLOCH}
dpkg -s moloch || dpkg -i #{MOLOCH}
SCRIPT

Vagrant.configure(2) do |config|
  (1..BOXES).each do |count|

    start = 15 + count
    name = ['moloch-cluster', NAME, 'box', count.to_s].join("-")
    ip = ['192.168.10', start.to_s].join(".")

    config.vm.define name do |box|
      box.vm.box = "ubuntu/bionic64"
      box.vm.hostname = name
      box.vm.network "public_network"
      box.vm.network :private_network, ip: ip
      box.vm.provider :virtualbox do |vb|
        vb.customize ["modifyvm", :id, "--memory", MEM_PER_BOX]
        vb.customize ["modifyvm", :id, "--cpus", CPU_PER_BOX]
      end
      box.vm.provider :hyperv do |hv, override|
        hv.cpus = CPU_PER_BOX
        hv.maxmemory = MEM_PER_BOX
        override.vm.box = "generic/ubuntu1804"
        override.vm.provision "shell", inline: $script
        #override.vm.synced_folder ".", "/vagrant", type: "smb"
      end
      box.vm.provision "shell", inline: $docker
      box.vm.provision "shell", inline: $moloch
    end
  end
  if SPLIT_DB_AND_MOLO == true

    id = 15 + BOXES + 20
    name = ['moloch-cluster', NAME, "ela"].join("-")
    ip = ['192.168.10', id.to_s].join(".")

    config.vm.define name do |box|
      box.vm.box = "ubuntu/bionic64"
      box.vm.hostname = name
      box.vm.network "public_network"
      box.vm.network :private_network, ip: ip
      box.vm.provider :virtualbox do |vb|
        vb.customize ["modifyvm", :id, "--memory", ELA_MEM]
        vb.customize ["modifyvm", :id, "--cpus", ELA_CPU]
      end
      box.vm.provider :hyperv do |hv, override|
        hv.cpus = ELA_CPU
        hv.maxmemory = ELA_MEM
        override.vm.box = "generic/ubuntu1804"
        override.vm.provision "shell", inline: $script
        #override.vm.synced_folder ".", "/vagrant", type: "smb"
      end
      box.vm.provision "shell", inline: $docker
    end
  end
end
