# vi: set ft=ruby :

# change if you want a dedicated alert box
DEPLOY_SEC = true

$buildSuricata = <<SCRIPT
export DEBIAN_FRONTEND=noninteractive
apt-get update && apt-get install -y libpcre3 libpcre3-dbg libpcre3-dev build-essential libpcap-dev libnet1-dev libyaml-0-2 libyaml-dev pkg-config zlib1g zlib1g-dev libcap-ng-dev libcap-ng0 make libmagic-dev libjansson-dev libnss3-dev libgeoip-dev liblua5.1-dev libhiredis-dev libevent-dev python-yaml rustc cargo build-essential autoconf automake libtool pkg-config make curl wget git unzip
git clone https://github.com/OISF/suricata
cd suricata
git clone https://github.com/OISF/libhtp.git -b 0.5.x
chown -R vagrant /home/vagrant/suricata
#./autogen.sh
#./configure --help
SCRIPT

Vagrant.configure(2) do |config|
  config.vm.provider :virtualbox do |vb|
    vb.customize ["modifyvm", :id, "--cpus", 2]
    vb.customize ["modifyvm", :id, "--memory", 2048]
  end
  config.vm.define 'client' do |box|
    box.vm.box = "janihur/ubuntu-1604-lxde-desktop"
    box.vm.hostname = 'client'
    box.vm.network :private_network, ip: "192.168.12.30", virtualbox__intnet: "INT"
    box.vm.provider :virtualbox do |vb|
      vb.gui = true
    end
  end
  config.vm.define 'bridge' do |box|
    box.vm.box = "ubuntu/bionic64"
    box.vm.hostname = 'bridge'
    box.vm.network :private_network, ip: "192.168.12.254", virtualbox__intnet: "INT"
    box.vm.provision "shell", inline: $buildSuricata
  end
end

