# -*- mode: ruby -*-
# vi: set ft=ruby :

$docker = <<-SCRIPT
export DEBIAN_FRONTEND=noninteractive
echo 'Acquire::ForceIPv4 "true";' | sudo tee /etc/apt/apt.conf.d/99force-ipv4
apt-get -qq -y install \
    apt-transport-https \
    ca-certificates \
    curl \
    gnupg-agent \
    software-properties-common
curl -fsSL https://download.docker.com/linux/ubuntu/gpg | apt-key add -
add-apt-repository \
   "deb [arch=amd64] https://download.docker.com/linux/ubuntu \
   $(lsb_release -cs) \
   stable"
apt-get update && apt-get install -qq -y docker-ce docker-ce-cli containerd.io
systemctl enable docker.service
systemctl start docker.service
adduser vagrant docker
SCRIPT

$swap = <<-SCRIPT
swapon --show | grep "NAME" && exit 1
dd if=/dev/zero of=/swapfile bs=1024 count=2097152
mkswap /swapfile
chmod 600 /swapfile
swapon /swapfile
swapon --show
SCRIPT

NAME="singlehost"
CPU=4
MEM=4096

Vagrant.configure(2) do |config|
  config.vm.define NAME do |box|
    box.vm.box = "generic/ubuntu2204"
    box.vm.hostname = NAME
    box.vm.network :private_network, ip: "192.168.56.10"
    box.vm.provider :virtualbox do |vb, override|
      override.vm.box = "ubuntu/jammy64"
      vb.customize ["modifyvm", :id, "--memory", MEM]
      vb.customize ["modifyvm", :id, "--cpus", CPU]
    end
    box.vm.provider "libvirt" do |v, override|
      v.cpus = CPU
      v.memory = MEM
    end
    box.vm.provider :hyperv do |hv, override|
      hv.cpus = CPU
      hv.maxmemory = MEM
      override.vm.synced_folder ".", "/vagrant", type: "smb"
    end
    box.vm.provider :vmware_desktop do |v, override|
      v.vmx["numvcpus"] = CPU
      v.vmx["memsize"] = MEM
    end
    box.vm.provision "shell", inline: $docker
    box.vm.provision "shell", inline: $swap
    box.vm.provision "shell", path: "provision.sh"
  end
end
