# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure(2) do |config|
  config.vm.define 'moloch' do |box|
    box.vm.box = "ubuntu/bionic64"
    box.vm.hostname = 'moloch-singlehost'
    box.vm.network :private_network, ip: "192.168.10.11"
    box.vm.provider :virtualbox do |vb|
      vb.customize ["modifyvm", :id, "--memory", "4096"]
      vb.customize ["modifyvm", :id, "--cpus", "4"]
    end
    box.vm.provider :hyperv do |hv, override|
      hv.cpus = 4
      hv.maxmemory = 4096
      override.vm.box = "generic/ubuntu1804"
    end
    config.vm.provision "docker", images: ["redis"]
    config.vm.provision "shell", path: "provision.sh"
  end
end
