$provision_script = <<SCRIPT

start=$(date)

cat >> /etc/sysctl.conf <<EOF
net.ipv6.conf.all.disable_ipv6 = 1
net.ipv6.conf.default.disable_ipv6 = 1
net.ipv6.conf.lo.disable_ipv6 = 1
EOF
sysctl -p

echo 'Acquire::ForceIPv4 "true";' | sudo tee /etc/apt/apt.conf.d/99force-ipv4
export DEBIAN_FRONTEND=noninteractive

#set versions here
#MOLOCH="moloch-nightly_amd64.deb"
MOLOCH=moloch_0.18.0-1_amd64.deb

echo "$(date) installing java"
add-apt-repository ppa:webupd8team/java
apt-get update
apt-get -y install oracle-java8-installer

cd /vagrant/
echo "$(date) installing moloch"
apt-get -y install libwww-perl libjson-perl
[[ -f $MOLOCH ]] || wget  -q -4 http://files.molo.ch/builds/ubuntu-16.04/$MOLOCH
#dpkg -i $MOLOCH || exit -1
#mv /data/moloch-nightly/ /data/moloch
confcmd=$(dpkg -i $MOLOCH | tail -1 | rev | cut -f1 -d" " | rev)

echo -en "enp0s3,enp0s8,lo\nno\nhttp://localhost:9200\ns2spassword\n" | $confcmd

echo "DONE :: start $start end $(date)"
netstat -ntple

SCRIPT

Vagrant.configure(2) do |config|
  config.vm.define 'moloch' do |box|
      box.vm.box = "ubuntu/xenial64"
      box.vm.hostname = 'moloch'
      box.vm.network :private_network, ip: "192.168.10.11"
      box.vm.provider :virtualbox do |vb|
       vb.customize ["modifyvm", :id, "--memory", "2048"]
       vb.customize ["modifyvm", :id, "--cpus", "2"]
      end
      config.vm.provision "shell", inline: $provision_script
  end
end
