# vi: set ft=ruby :

MASTER_IP = '192.168.10.20'
MASTER_CPU = 2
MASTER_MEM = 1024
MASTER_IMG = 'ubuntu/xenial64'

SALT = 'stable'

boxes = [
  {
    :name       => "minion-1",
    :mem        => "2048",
    :cpu        => "2",
    :ip         => "192.168.10.21",
    :image      => 'ubuntu/xenial64',
    :provision  => []
  },
  {
    :name       => "minion-2",
    :mem        => "2048",
    :cpu        => "2",
    :ip         => "192.168.10.22",
    :image      => 'ubuntu/xenial64',
    :provision  => []
  },
  {
    :name       => "minion-3",
    :mem        => "2048",
    :cpu        => "2",
    :ip         => "192.168.10.23",
    :image      => 'ubuntu/xenial64',
    :provision  => []
  },
  {
    :name       => "minion-4",
    :mem        => "2048",
    :cpu        => "2",
    :ip         => "192.168.10.24",
    :image      => 'ubuntu/xenial64',
    :provision  => []
  }
]

Vagrant.configure(2) do |config|
  # provision master separately
  config.vm.define 'master' do |master|
    master.vm.box = MASTER_IMG 
    master.vm.hostname = 'master'
    master.vm.network :private_network, ip: MASTER_IP
    master.vm.provider :virtualbox do |vb|
      vb.customize ["modifyvm", :id, "--cpus", MASTER_CPU]
      vb.customize ["modifyvm", :id, "--memory", MASTER_MEM]
    end
    master.vm.provision :salt do |salt|
      salt.master_config = "conf/master"
      salt.masterless = false
      salt.run_highstate = false
      salt.install_type = SALT
      salt.install_master = true
    end
  end
  # provision workers as defined by user
  boxes.each do |opts|
    config.vm.define opts[:name] do |config|
      config.vm.box = opts[:image]
      config.vm.hostname = opts[:name]
      config.vm.network 'private_network',
        ip: opts[:ip]
      config.vm.provider "virtualbox" do |v|
        v.customize ["modifyvm", :id, "--memory", opts[:mem]]
        v.customize ["modifyvm", :id, "--cpus", opts[:cpu]]
      end
      config.vm.provision "shell",
        inline: "grep salt /etc/hosts || sudo echo \"#{MASTER_IP}\"  salt >> /etc/hosts"
      config.vm.provision :salt do |salt|
        salt.minion_config = "conf/minion"
        salt.masterless = false
        salt.run_highstate = false
        salt.install_type = SALT
        salt.install_master = false
      end
    end
  end
end
