# -*- mode: ruby -*-
# vi: set ft=ruby :

$provision_script = <<SCRIPT

WGET_PARAMS="-4 -q"

START=`date`
echo "Building Suricata ..."
apt-get update && apt-get -qq -y install \
libpcre3 \
libpcre3-dbg \
libpcre3-dev \
build-essential \
autoconf \
automake \
libtool \
libpcap-dev \
libnet1-dev \
libyaml-0-2 \
libyaml-dev \
pkg-config \
zlib1g \
zlib1g-dev \
libcap-ng-dev \
libcap-ng0 \
make \
libmagic-dev \
libnss3-dev \
libelf-dev \
libjansson-dev \
curl \
wget \
git \
clang \
unzip \
rustc \
cargo

cargo install --force cbindgen
ln -s /root/.cargo/bin/cbindgen /bin/cbindgen

apt-get -qq -y install \
libelf-dev \
linux-headers-amd64 \
git \
liblz4-dev \
binutils-dev \
python3-pip \
python3-distutils

apt-get -qq -y install libc6-dev-i386 --no-install-recommends

mkdir /data && cd /data

[[ -d libbpf ]] || git clone https://github.com/libbpf/libbpf.git
[[ -d bpfctrl ]] || git clone https://github.com/StamusNetworks/bpfctrl.git
if [[ ! -d linux-4.19.102 ]] ; then
  wget -4 -q https://cdn.kernel.org/pub/linux/kernel/v4.x/linux-4.19.102.tar.xz
  tar -xJf linux-4.19.102.tar.xz
fi

[[ -d suricata ]] || git clone https://github.com/oisf/suricata.git
cd suricata

[[ -d libhtp ]] || git clone https://github.com/OISF/libhtp.git
cd libhtp && git checkout tags/0.5.32 && cd ..

pwd
./autogen.sh
cd ..

END=`date`

echo started at $START
echo finished at $END

echo "NOW YOU CAN BUILD AN EBPF/XDP SURICATA"
echo "see: https://github.com/ccdcoe/CDMCS/blob/master/Suricata/ebpf/README.md for tasks"

SCRIPT

Vagrant.configure(2) do |config|
  config.vm.define 'buildEBPF' do |box|
      box.vm.box = "debian/buster64"
      box.vm.hostname = 'buildEBPF'
      box.vm.network :private_network, ip: "192.168.56.16"
      box.vm.provider :virtualbox do |vb|
       vb.customize ["modifyvm", :id, "--memory", "2048"]
       vb.customize ["modifyvm", :id, "--cpus", "4"]
      end
  end
  config.vm.provision "shell", inline: $provision_script
end
