
studentNumber = 19

$teleconfig = "../../scripts/minion.provision.bash"
$masterinstall = "../../scripts/master.provision.bash"
MASTEROFMASTERS = "192.168.128.201"
NET = "10.244.1."
NET_START = 10
STUDENTCOUNT = 1
SURICATACOUNT = 2

Vagrant.configure(2) do |config|
  config.vm.box = "vsphere"
  config.vm.synced_folder ".", "/vagrant", disabled: true
  require '../../../../../../../../keys/vm.rb'
  include VMKeys
  config.ssh.username = VM_USER # the one used to create the VM
  config.ssh.password = VM_PASSWORD # the one used to create the VM
  require '../../../../../../../../keys/vsphere.rb'
  include VSphereKeys
  config.vm.provider :vsphere do |vsphere|
    vsphere.host = VSPHERE_HOST
    vsphere.data_center_name = VSPHERE_DC
    vsphere.compute_resource_name = VSPHERE_CLUSTER
    vsphere.template_name = VSPHERE_TEMPLATE_PATH + 'student-X-master'
    #vsphere.vm_base_path = VSPHERE_VM_PATH + 'Student_' + studentNumber.to_s
    vsphere.customization_spec_name = 'linux_1nics'
    vsphere.user = VSPHERE_USER
    vsphere.password = VSPHERE_PASSWORD
    vsphere.insecure = true
  end

#  (1..STUDENTCOUNT).each do |studentNumber|

    ipm = NET  + (NET_START + (studentNumber-1)*10).to_s

    name = 'student-'+studentNumber.to_s+'-master'
    puts "#{ipm} #{name}"
    config.vm.define name do |box|
      box.vm.hostname = name
      box.vm.network 'private_network', ip: ipm
      box.vm.provision "shell", path: $teleconfig, args: "#{MASTEROFMASTERS} #{ipm} #{ipm} "
      box.vm.provision "shell", path: $masterinstall, args: "#{ipm}"
      box.vm.provider :vsphere do |vsphere|
        vsphere.memory_mb = 4 * 1024
        vsphere.cpu_count = 4
        vsphere.vm_base_path = VSPHERE_VM_PATH + 'Student_' + studentNumber.to_s
      end
    end

    (1..SURICATACOUNT).each do |counter|
      ip = NET  + (NET_START + ((studentNumber-1)*10)+counter).to_s
      namet = 'student-'+studentNumber.to_s+'-minion-'+counter.to_s
      puts "#{ip} #{namet}"
      config.vm.define namet do |boxt|
        boxt.vm.hostname = namet
        boxt.vm.network 'private_network', ip: ip
        boxt.vm.provision "shell", path: $teleconfig, args: "#{ipm} #{ip} "
        boxt.vm.provider :vsphere do |vsphere|
          vsphere.memory_mb = 4 * 512
          vsphere.cpu_count = 2
          vsphere.vm_base_path = VSPHERE_VM_PATH + 'Student_' + studentNumber.to_s
        end
      end
    end
#  end
end
