# -*- mode: ruby -*-
# vi: set ft=ruby :

$provision_script = <<SCRIPT
apt-get update && apt-get -y install python3 python3-pip

su vagrant -c "python3 -m pip install --user --upgrade pip"
su vagrant -c "python3 -m pip install --user --upgrade jupyter"
su vagrant -c "python3 -m pip install --user --upgrade jupyterlab"
SCRIPT

Vagrant.configure(2) do |config|
  config.vm.define 'clusterbox' do |box|
    box.vm.box = "ubuntu/bionic64"
    box.vm.hostname = 'clusterbox'
    box.vm.network "public_network"
    box.vm.network :private_network, ip: "192.168.10.15"
    box.vm.provider :virtualbox do |vb|
      vb.customize ["modifyvm", :id, "--memory", "4096"]
      vb.customize ["modifyvm", :id, "--cpus", "4"]
    end
    box.vm.provision "docker", images: [
      "redis",
      "docker.elastic.co/elasticsearch/elasticsearch-oss:6.6.0",
      "docker.elastic.co/kibana/kibana-oss:6.6.0",
      "docker.elastic.co/logstash/logstash-oss:6.6.0",
      "jasonish/evebox"
    ]
    box.vm.provision "shell", path: "provision.sh"
    box.vm.provision "shell", inline: $provision_script
    box.vm.synced_folder "../vagrant/singlehost", "/singlehost"
    box.vm.synced_folder "./", "/home/vagrant/localbox"
  end
end
