# vi: set ft=ruby :

# change if you want a dedicated alert box
DEPLOY_SEC = false

$buildSuricata = <<SCRIPT
export DEBIAN_FRONTEND=noninteractive
apt-get update && apt-get build-dep suricata -y
git clone https://github.com/OISF/suricata
cd suricata
git clone https://github.com/OISF/libhtp.git -b 0.5.x
./autogen.sh
./configure --help
SCRIPT

$setupWebServer = <<SCRIPT
export DEBIAN_FRONTEND=noninteractive
apt-get update && apt-get install -y nginx
SCRIPT

Vagrant.configure(2) do |config|
  config.vm.provider :virtualbox do |vb|
    vb.customize ["modifyvm", :id, "--cpus", 2]
    vb.customize ["modifyvm", :id, "--memory", 2048]
  end
  config.vm.define 'client' do |box|
    box.vm.box = "janihur/ubuntu-1604-lxde-desktop"
    box.vm.hostname = 'client'
    box.vm.network :private_network, ip: "192.168.12.30", virtualbox__intnet: "INT"
    box.vm.provider :virtualbox do |vb|
      vb.gui = true
    end
  end
  config.vm.define 'bridge' do |box|
    box.vm.box = "ubuntu/xenial64"
    box.vm.hostname = 'bridge'
    box.vm.network :private_network, ip: "192.168.12.254", virtualbox__intnet: "INT"
    box.vm.network :private_network, ip: "192.168.10.30"
    box.vm.provision "shell", inline: $buildSuricata
  end
  if DEPLOY_SEC == true
    config.vm.define 'sec' do |box|
      box.vm.box = "ubuntu/xenial64"
      box.vm.hostname = 'sec'
      box.vm.network :private_network, ip: "192.168.10.31"
      config.vm.provider :virtualbox do |vb|
        vb.customize ["modifyvm", :id, "--cpus", 4]
        vb.customize ["modifyvm", :id, "--memory", 4096]
      end
    end
  end
end

