$provision_script = <<SCRIPT

GOLANG="go1.7.4.linux-amd64.tar.gz"

mkdir -p /tests
cd /tests
wget -q -4 https://storage.googleapis.com/golang/$GOLANG
tar -zxvf $GOLANG -C /usr/local/ > /dev/null 2>&1
echo 'export GOROOT=/usr/local/go' >> ~/.bashrc
echo 'export PATH=$PATH:$GOROOT/bin:$GOPATH/bin' >> ~/.bashrc
echo 'export GOPATH=/tests' >> ~/.bashrc
export GOROOT=/usr/local/go
export PATH=$PATH:$GOROOT/bin:$GOPATH/bin
export GOPATH=/tests
go version
go env
time go get github.com/influxdata/telegraf


SCRIPT

Vagrant.configure(2) do |config|
  config.vm.define 'buildTelegraf' do |box|
      box.vm.box = "ubuntu/xenial64"
      box.vm.hostname = 'buildTelegraf'
      box.vm.network :private_network, ip: "192.168.11.12"
      box.vm.provider :virtualbox do |vb|
       vb.customize ["modifyvm", :id, "--memory", "2048"]
       vb.customize ["modifyvm", :id, "--cpus", "2"]
      end
      config.vm.provision "shell", inline: $provision_script
  end
end
