# -*- mode: ruby -*-
# vi: set ft=ruby :
$arkime = <<-SCRIPT
ARKIME_VERSION="5.1.2"
UBUNTU_VERSION="2204"

ARKIME_LINK="https://github.com/arkime/arkime/releases/download/v${ARKIME_VERSION}/arkime_${ARKIME_VERSION}-1.ubuntu${UBUNTU_VERSION}_amd64.deb"
ARKIME_JA4_LINK="https://github.com/arkime/arkime/releases/download/v${ARKIME_VERSION}/ja4plus.amd64.so"

wget $ARKIME_LINK
wget $ARKIME_JA4_LINK
pwd
SCRIPT

$swap = <<-SCRIPT
swapon --show | grep "NAME" && exit 1
dd if=/dev/zero of=/swapfile bs=1024 count=2097152
mkswap /swapfile
chmod 600 /swapfile
swapon /swapfile
swapon --show
SCRIPT

NAME="setup"
CPU=4
MEM=4096

Vagrant.configure(2) do |config|
  config.vm.define NAME do |box|
    box.vm.box = "generic/ubuntu2204"
    box.vm.hostname = NAME
    box.vm.network :private_network, ip: "192.168.56.12"
    box.vm.provider :virtualbox do |vb|
      vb.customize ["modifyvm", :id, "--memory", MEM]
      vb.customize ["modifyvm", :id, "--cpus", CPU]
    end
    box.vm.provider "libvirt" do |v, override|
      v.cpus = CPU
      v.memory = MEM
    end
    box.vm.provider :hyperv do |hv, override|
      hv.cpus = CPU
      hv.maxmemory = MEM
      override.vm.synced_folder ".", "/vagrant", type: "smb"
    end
    box.vm.provider :vmware_desktop do |v, override|
      v.vmx["numvcpus"] = CPU
      v.vmx["memsize"] = MEM
    end
    box.vm.provision "docker", images: [
      "docker.elastic.co/elasticsearch/elasticsearch:8.13.4",
      "redis"
    ]
    box.vm.provision "shell", inline: $swap
    box.vm.provision "shell", inline: $arkime
  end
end
